name: Run Unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft' 
          java-version: '17'
      - name: Install poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run test
        run: |
          javac -encoding UTF-8 *.java  -target 8 -source 8
          poetry run python -m pytest ./tests
